// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package bitcaskdb

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockStorageFile creates a new instance of MockStorageFile. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorageFile(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorageFile {
	mock := &MockStorageFile{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorageFile is an autogenerated mock type for the StorageFile type
type MockStorageFile struct {
	mock.Mock
}

type MockStorageFile_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorageFile) EXPECT() *MockStorageFile_Expecter {
	return &MockStorageFile_Expecter{mock: &_m.Mock}
}

// Append provides a mock function for the type MockStorageFile
func (_mock *MockStorageFile) Append(data []byte) error {
	ret := _mock.Called(data)

	if len(ret) == 0 {
		panic("no return value specified for Append")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]byte) error); ok {
		r0 = returnFunc(data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorageFile_Append_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Append'
type MockStorageFile_Append_Call struct {
	*mock.Call
}

// Append is a helper method to define mock.On call
//   - data []byte
func (_e *MockStorageFile_Expecter) Append(data interface{}) *MockStorageFile_Append_Call {
	return &MockStorageFile_Append_Call{Call: _e.mock.On("Append", data)}
}

func (_c *MockStorageFile_Append_Call) Run(run func(data []byte)) *MockStorageFile_Append_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []byte
		if args[0] != nil {
			arg0 = args[0].([]byte)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStorageFile_Append_Call) Return(err error) *MockStorageFile_Append_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorageFile_Append_Call) RunAndReturn(run func(data []byte) error) *MockStorageFile_Append_Call {
	_c.Call.Return(run)
	return _c
}

// CanAppend provides a mock function for the type MockStorageFile
func (_mock *MockStorageFile) CanAppend(size int) bool {
	ret := _mock.Called(size)

	if len(ret) == 0 {
		panic("no return value specified for CanAppend")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(int) bool); ok {
		r0 = returnFunc(size)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockStorageFile_CanAppend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CanAppend'
type MockStorageFile_CanAppend_Call struct {
	*mock.Call
}

// CanAppend is a helper method to define mock.On call
//   - size int
func (_e *MockStorageFile_Expecter) CanAppend(size interface{}) *MockStorageFile_CanAppend_Call {
	return &MockStorageFile_CanAppend_Call{Call: _e.mock.On("CanAppend", size)}
}

func (_c *MockStorageFile_CanAppend_Call) Run(run func(size int)) *MockStorageFile_CanAppend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStorageFile_CanAppend_Call) Return(b bool) *MockStorageFile_CanAppend_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockStorageFile_CanAppend_Call) RunAndReturn(run func(size int) bool) *MockStorageFile_CanAppend_Call {
	_c.Call.Return(run)
	return _c
}

// FileID provides a mock function for the type MockStorageFile
func (_mock *MockStorageFile) FileID() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FileID")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockStorageFile_FileID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FileID'
type MockStorageFile_FileID_Call struct {
	*mock.Call
}

// FileID is a helper method to define mock.On call
func (_e *MockStorageFile_Expecter) FileID() *MockStorageFile_FileID_Call {
	return &MockStorageFile_FileID_Call{Call: _e.mock.On("FileID")}
}

func (_c *MockStorageFile_FileID_Call) Run(run func()) *MockStorageFile_FileID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorageFile_FileID_Call) Return(n int) *MockStorageFile_FileID_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockStorageFile_FileID_Call) RunAndReturn(run func() int) *MockStorageFile_FileID_Call {
	_c.Call.Return(run)
	return _c
}

// ReadAt provides a mock function for the type MockStorageFile
func (_mock *MockStorageFile) ReadAt(position int64, size int) ([]byte, error) {
	ret := _mock.Called(position, size)

	if len(ret) == 0 {
		panic("no return value specified for ReadAt")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int64, int) ([]byte, error)); ok {
		return returnFunc(position, size)
	}
	if returnFunc, ok := ret.Get(0).(func(int64, int) []byte); ok {
		r0 = returnFunc(position, size)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int64, int) error); ok {
		r1 = returnFunc(position, size)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorageFile_ReadAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadAt'
type MockStorageFile_ReadAt_Call struct {
	*mock.Call
}

// ReadAt is a helper method to define mock.On call
//   - position int64
//   - size int
func (_e *MockStorageFile_Expecter) ReadAt(position interface{}, size interface{}) *MockStorageFile_ReadAt_Call {
	return &MockStorageFile_ReadAt_Call{Call: _e.mock.On("ReadAt", position, size)}
}

func (_c *MockStorageFile_ReadAt_Call) Run(run func(position int64, size int)) *MockStorageFile_ReadAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int64
		if args[0] != nil {
			arg0 = args[0].(int64)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorageFile_ReadAt_Call) Return(bytes []byte, err error) *MockStorageFile_ReadAt_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockStorageFile_ReadAt_Call) RunAndReturn(run func(position int64, size int) ([]byte, error)) *MockStorageFile_ReadAt_Call {
	_c.Call.Return(run)
	return _c
}

// Size provides a mock function for the type MockStorageFile
func (_mock *MockStorageFile) Size() int64 {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Size")
	}

	var r0 int64
	if returnFunc, ok := ret.Get(0).(func() int64); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int64)
	}
	return r0
}

// MockStorageFile_Size_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Size'
type MockStorageFile_Size_Call struct {
	*mock.Call
}

// Size is a helper method to define mock.On call
func (_e *MockStorageFile_Expecter) Size() *MockStorageFile_Size_Call {
	return &MockStorageFile_Size_Call{Call: _e.mock.On("Size")}
}

func (_c *MockStorageFile_Size_Call) Run(run func()) *MockStorageFile_Size_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorageFile_Size_Call) Return(n int64) *MockStorageFile_Size_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockStorageFile_Size_Call) RunAndReturn(run func() int64) *MockStorageFile_Size_Call {
	_c.Call.Return(run)
	return _c
}
